CREATE STOGROUP SG_TUGAS1
ON '/db2tugas1'
DATA TAG NONE;

CREATE BUFFERPOOL BP18KB PAGESIZE 8192;
CREATE BUFFERPOOL BP24KB PAGESIZE 4096;

CREATE REGULAR TABLESPACE TB1_4K
PAGESIZE 4096
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_TUGAS1
AUTORESIZE YES
BUFFERPOOL BP24KB;

CREATE LARGE TABLESPACE TB2_8K
PAGESIZE 8192
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_TUGAS1
AUTORESIZE YES
BUFFERPOOL BP18KB;

CREATE REGULAR TABLESPACE IDX_4K
PAGESIZE 4096
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_TUGAS1
AUTORESIZE YES
BUFFERPOOL BP24KB;

CREATE TABLE JURUSAN(
	ID_JURUSAN SMALLINT NOT NULL PRIMARY KEY,
	JURUSAN VARCHAR(30) NOT NULL UNIQUE
)
IN TB1_4K
INDEX IN IDX_4K;

CREATE TABLE SELEKSI_MASUK(
	ID_SELEKSI_MASUK SMALLINT NOT NULL PRIMARY KEY,
	SELEKSI_MASUK VARCHAR(20) NOT NULL UNIQUE
)
IN TB1_4K
INDEX IN IDX_4K;

DROP TABLE MAHASISWA;

CREATE TABLE MAHASISWA(
	NIM VARCHAR(20) NOT NULL PRIMARY KEY,
	NAMA VARCHAR(30),
	ID_JURUSAN SMALLINT REFERENCES JURUSAN,
	ID_SELEKSI_MASUK SMALLINT REFERENCES SELEKSI_MASUK
)
IN TB2_8K
INDEX IN IDX_4K;
